#:schema node_modules/wrangler/config-schema.json
name = "dane-computer"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }

[observability]
enabled = true
