name: Renovate
on:
  schedule:
    - cron: "0 9 * * 1"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.6
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
